sampler_config: &id003
  method: mix
  num_samples: 65536
  vertex_samples: 8192
tail_config: &id001
  copy_joint_to_tail: false
  connect_tail_to_unique_son: true
order_config: &id002
  skeleton_path:
    vroid: ./configs/skeleton/vroid.yaml
    mixamo: ./configs/skeleton/mixamo.yaml
vertex_group_config: null
validate_transform_config: &id004
  augment_config:
    augment_affine_config:
      normalize_into:
      - -1.0
      - 1.0
      random_scale_p: 0.0
      random_scale:
      - 1.0
      - 1.0
      random_shift_p: 0.0
      random_shift:
      - 0.0
      - 0.0
  tail_config: *id001
  order_config: *id002
  vertex_group_config: null
  sampler_config: *id003
predict_transform_config: *id004
