mode: predict
debug: false
experiment_name: peasant_local_skin
resume_from_checkpoint: /home/sean/workspace/shape-gen/models/unirig/skin/articulation-xl/model.ckpt
components:
  data: /home/sean/workspace/shape-gen/config/unirig/data.yaml
  transform: /home/sean/workspace/shape-gen/config/unirig/skin-transform.yaml
  model: /home/sean/workspace/shape-gen/config/unirig/skin-model.yaml
  system: skin
  data_name: predict_skeleton.npz
writer:
  __target__: skin
  output_dir: null
  add_num: false
  repeat: 1
  save_name: predict
  export_npz: predict_skin
  export_fbx: null
  export_obj: null
trainer:
  num_nodes: 1
  devices: 1
  precision: bf16-mixed
  accelerator: gpu
  strategy: auto
  inference_mode: true
  enable_checkpointing: false
  enable_model_summary: false
  enable_progress_bar: false
  default_root_dir: /home/sean/workspace/shape-gen/assets/peasant-unirig/logs
