"""Build docs/INDEX.md from a deliberately small, dependency-free YAML subset."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIELDS = ('title', 'summary', 'kind', 'status', 'topics', 'read_when')
KINDS = ('setup', 'reference', 'operations', 'research', 'history')
STATUSES = ('current', 'experimental', 'historical')


def metadata(path):
    lines = path.read_text(encoding='utf-8').splitlines()
    if not lines or lines[0] != '---':
        raise ValueError(f'{path}: missing frontmatter')
    try:
        end = lines.index('---', 1)
    except ValueError as error:
        raise ValueError(f'{path}: unclosed frontmatter') from error
    result = {}
    for line in lines[1:end]:
        if not line.strip() or line.lstrip().startswith('#'):
            continue
        key, sep, raw = line.partition(':')
        if not sep or key in result or key not in FIELDS:
            raise ValueError(f'{path}: unknown, duplicate or malformed field: {line}')
        try:
            result[key] = json.loads(raw)
        except json.JSONDecodeError as error:
            raise ValueError(f'{path}: use a JSON-quoted string or array for {key}') from error
    if set(result) != set(FIELDS):
        raise ValueError(f'{path}: required fields: {", ".join(FIELDS)}')
    for key in FIELDS:
        values = result[key] if key == 'topics' else [result[key]]
        if not isinstance(values, list) or not values or any(
                not isinstance(v, str) or not v.strip() or '\n' in v or '\r' in v for v in values):
            raise ValueError(f'{path}: {key} must contain nonempty single-line strings')
    if result['kind'] not in KINDS or result['status'] not in STATUSES:
        raise ValueError(f'{path}: invalid kind or status')
    return result


def cell(value):
    return value.replace('|', '&#124;').replace('<', '&lt;').replace('>', '&gt;')


def render(directory):
    entries = [(p.relative_to(directory).as_posix(), metadata(p))
               for p in sorted(directory.rglob('*.md')) if p != directory / 'INDEX.md']
    header = dict(title='Documentation index', summary='Generated routing summaries for all maintained docs.',
                  kind='reference', status='current', topics=['documentation', 'navigation'],
                  read_when='Start here to choose the smallest relevant document before reading details.')
    lines = ['---', *(f'{k}: {json.dumps(v, ensure_ascii=False)}' for k, v in header.items()), '---',
             '# Documentation index', '',
             '<!-- Generated by scripts/build_docs_index.py; edit source frontmatter, not this file. -->', '',
             'Read the summary and “Read when” column, then open the relevant document. '
             'Historical evidence does not override current setup or API contracts.', '',
             'Start with the [project README](../README.md). '
             'For documentation maintenance see [the conventions](documentation.md).', '',
             f'{len(entries)} documents. Rebuild: `python3 scripts/build_docs_index.py`; '
             'verify: `python3 scripts/build_docs_index.py --check`.', '']
    for kind in KINDS:
        selected = [(name, m) for name, m in entries if m['kind'] == kind]
        if not selected:
            continue
        lines.extend([f'## {kind.title()}', '', '| Document | Status / topics | Summary | Read when |',
                      '|---|---|---|---|'])
        for name, m in selected:
            lines.append(f'| [{cell(m["title"])}]({name}) | {m["status"]}; {cell(", ".join(m["topics"]))} | '
                         f'{cell(m["summary"])} | {cell(m["read_when"])} |')
        lines.append('')
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--docs-dir', type=Path, default=ROOT / 'docs')
    parser.add_argument('--check', action='store_true', help='Fail for invalid metadata or an outdated index; no writes')
    args = parser.parse_args()
    if not args.docs_dir.is_dir():
        parser.error('Documentation directory does not exist')
    try:
        content = render(args.docs_dir)
    except ValueError as error:
        parser.exit(1, f'{error}\n')
    output = args.docs_dir / 'INDEX.md'
    if args.check:
        if not output.exists() or output.read_text(encoding='utf-8') != content:
            parser.exit(1, 'Documentation index is stale; run scripts/build_docs_index.py\n')
        print('Documentation metadata and index are current.')
    else:
        output.write_text(content, encoding='utf-8')
        print(f'Wrote {output}')


if __name__ == '__main__':
    main()
